name: Simple Test

on: [push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install -y openjdk-11-jdk maven nodejs npm
      - run: npx playwright install chromium
      - run: mvn test