name: Submit Task

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup environment
      run: |
        sudo apt update
        sudo apt install -y openjdk-11-jdk maven nodejs npm
        npm install -g playwright
        npx playwright install chromium
        
    - name: Execute tests
      run: |
        mvn test
        
    - name: Success
      if: success()
      run: echo "Всё норм"